version: '3'
services:
  swagger:
    image: swaggerapi/swagger-ui
    env_file:
      - .env
    depends_on:
      - api
    ports:
      - '8080:8080'
  postgresql:
    image: postgres
    env_file:
      - .env
  api:
    build: ./src
    env_file:
      - .env
    command: tail -f /dev/null
    volumes:
      - ./src:/app
    links:
      - 'postgresql:postgresql'
    depends_on:
      - postgresql
    ports:
      - '3000:3000'
