---
detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    public_methods_only: true
    exclude:
      - 'Factory#create_post'

  UncommunicativeModuleName:
    accept:
      - 'V1'

directories:
  'db/migrate':
    FeatureEnvy:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    TooManyStatements:
      enabled: false
