source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'rails', '~> 5.2.1'

# Use postgresql as the database for Active Record
gem 'pg'

# Use Thin as the app server
gem 'thin'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# API
gem 'grape'
gem 'grape-entity'
gem 'grape_logging', '~> 1.3'
gem 'grape-swagger-entity'

gem 'oj'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  gem 'pry-byebug'
  gem 'grape_on_rails_routes'
end

group :development do
  gem 'listen'
end
