# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'rails', '~> 5.2.1'

# Use postgresql as the database for Active Record
gem 'pg'

# Use Thin as the app server
gem 'thin'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# API
gem 'grape'
gem 'grape-entity'
gem 'grape-swagger-entity'
gem 'grape_logging', '~> 1.3'

gem 'dry-transaction'
gem 'oj'

gem 'rack-cors', require: 'rack/cors'

group :development, :test do
  gem 'grape_on_rails_routes'
  gem 'pry-byebug'

  gem 'faker'
  gem 'rspec-rails'
end

group :development do
  gem 'listen'
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
end

group :test do
  gem 'json_matchers'
end
